version: "3.9"
services:
  gateway:
    build: .
    environment:
      - SERVICE=gateway
      - PORT=8000
      - MARTECH_URL=http://martech:8000
      - PROPERTY_URL=http://property:8000
    ports:
      - "8080:8000"

  martech:
    build: .
    environment:
      - SERVICE=martech
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./local.db}
      - OUTBOUND_HTTP_PROXY=${OUTBOUND_HTTP_PROXY:-}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
    ports:
      - "8081:8000"

  property:
    build:
      context: ./services/property
    environment:
      - SERVICE=property
      - PORT=8000
    ports:
      - "8082:8000"

  interface:
    build:
      context: ./interface
    environment:
      - PORT=3000
      - VITE_API_BASE_URL=http://gateway:8000
    depends_on:
      - gateway
    ports:
      - "5173:3000"
    profiles:
      - ui
