version: "3.9"
services:
  gateway:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
      args:
        SERVICE: gateway
    environment:
      - SERVICE=gateway
      - PORT=8000
      - MARTECH_URL=http://martech:8000
      - PROPERTY_URL=http://property:8000
      - UI_ORIGIN=${UI_ORIGIN:-http://localhost:5173}
    ports:
      - "8080:8000"

  martech:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
      args:
        SERVICE: martech
    environment:
      - SERVICE=martech
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./local.db}
      - OUTBOUND_HTTP_PROXY=${OUTBOUND_HTTP_PROXY:-}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - UI_ORIGIN=${UI_ORIGIN:-http://localhost:5173}
    ports:
      - "8081:8000"

  property:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
      args:
        SERVICE: property
    environment:
      - SERVICE=property
      - PORT=8000
      - UI_ORIGIN=${UI_ORIGIN:-http://localhost:5173}
    ports:
      - "8082:8000"

  insight:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
      args:
        SERVICE: insight
    environment:
      - SERVICE=insight
      - PORT=8000
      - UI_ORIGIN=${UI_ORIGIN:-http://localhost:5173}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "8083:8000"

  interface:
    build:
      context: ./interface
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8080}
    environment:
      - PORT=3000
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8080}
    depends_on:
      - gateway
    ports:
      - "5173:3000"
    profiles:
      - ui
