version: "3.9"
services:
  gateway:
    build: .
    environment:
      - SERVICE=gateway
      - PORT=8000
      - MARTECH_URL=http://martech:8000
    ports:
      - "8080:8000"

  martech:
    build: .
    environment:
      - SERVICE=martech
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./local.db}
    ports:
      - "8081:8000"
