version: "3.9"
services:
  gateway:
    build: ./services/gateway
    ports:
      - "8000:80"
    environment:
      MARTECH_URL: "http://martech:80"

  martech:
    build: ./services/martech
    ports:
      - "8001:80"
