# Force Railway to use Dockerfile builder
[build]
builder = "DOCKERFILE"

# Service definitions
[[services]]
name = "property"
projectPath = "services/property"
dockerfilePath = "services/property/Dockerfile"
startCommand = "uvicorn app:app --host 0.0.0.0 --port 80"

[[services]]
name = "martech"
projectPath = "services/martech"
dockerfilePath = "services/martech/Dockerfile"
startCommand = "uvicorn app:app --host 0.0.0.0 --port 80"

# (Optional) Future services:
# [[services]]
# name = "gateway"
# projectPath = "services/gateway"
# dockerfilePath = "services/gateway/Dockerfile"
# startCommand = "uvicorn gateway.main:app --host 0.0.0.0 --port 80"
