# Root-level Railway config
projectPath = "."
branch = "main"
environment = "production"

# Gateway service
[[services]]
name = "unitron"
projectPath = "services/gateway"
dockerfilePath = "Dockerfile"
startCommand = "uvicorn app:app --host 0.0.0.0 --port 80"
healthcheckPath = "/health"

# Martech service
[[services]]
name = "martech"
projectPath = "services/martech"
dockerfilePath = "Dockerfile"
startCommand = "uvicorn app:app --host 0.0.0.0 --port 80"
healthcheckPath = "/health"
