"$schema" = "https://railway.com/railway.schema.json"

[build]
builder = "DOCKERFILE"

[deploy]
# default health path & timeouts for all services
healthcheckPath    = "/health"
healthcheckTimeout = 10
healthcheckDelay   = 5

[[services]]
name        = "unitron"
projectPath = "services/gateway"
startCommand = "sh -c \"uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}\""
instances    = 1  

[[services]]
name        = "martech"
projectPath = "services/martech"
startCommand = "sh -c \"uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}\""
instances    = 1  
