schema = "https://railway.com/railway.schema.json"

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath     = "/health"
healthcheckTimeout  = 5000
healthcheckInterval = 2000

[[services]]
name         = "gateway"
projectPath  = "."
startCommand = "SERVICE=gateway uvicorn gateway.app:app --host 0.0.0.0 --port $PORT"
instances    = 1

[[services]]
name         = "martech"
projectPath  = "."
startCommand = "SERVICE=martech uvicorn martech.app:app --host 0.0.0.0 --port $PORT"
instances    = 1
