$schema = "https://railway.com/railway.schema.json"

[deploy]
healthcheckPath    = "/health"
healthcheckTimeout = 5000
healthcheckInterval = 2000

[[services]]
name         = "gateway"
projectPath  = "."
dockerfilePath = "services/gateway/Dockerfile"
startCommand = "sh -c \"uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}\""
instances    = 1

[[services]]
name         = "martech"
projectPath  = "."
dockerfilePath = "services/martech/Dockerfile"
startCommand = "sh -c \"uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}\""
instances    = 1
