[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"  # root-level Dockerfile

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port 80"
healthcheckPath = "/docs"

# Environment variables stay in the Railway dashboard (OPENAI_API_KEY, PG*)
