# Root-level Railway config
projectPath = "."
branch = "main"
environment = "production"

# Gateway service
[[services]]
name = "unitron"
projectPath = "services/gateway"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

# Martech service
[[services]]
name = "martech"
projectPath = "services/martech"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"
