"$schema" = "https://railway.com/railway.schema.json"

[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath    = "/health"
healthcheckTimeout = 30

[[services]]
name        = "unitron"
projectPath = "services/gateway"
startCommand = "sh -c \"uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}\""

[[services]]
name        = "martech"
projectPath = "services/martech"
startCommand = "sh -c \"uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}\""
