# Force Railway to use Dockerfile builds for each micro-service
[build]
engine = "docker"

[[services]]
name          = "property"
projectPath   = "services/property"   # folder that contains the Dockerfile
dockerfilePath = "Dockerfile"         # relative to projectPath
startCommand  = "uvicorn app:app --host 0.0.0.0 --port 80"

[[services]]
name          = "martech"
projectPath   = "services/martech"
dockerfilePath = "Dockerfile"
startCommand  = "uvicorn app:app --host 0.0.0.0 --port 80"

# (Add more services — gateway, n8n, etc. — using the same pattern)
