# Root-level Railway config
projectPath = "."
branch = "main"
environment = "production"

# Gateway service
[[services]]
name = "unitron"
projectPath = "."
dockerfilePath = "services/gateway/Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

# Martech service
[[services]]
name = "martech"
projectPath = "."
dockerfilePath = "services/martech/Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

# Property service
[[services]]
name = "property"
projectPath = "."
dockerfilePath = "services/property/Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"
