schema = "https://railway.com/railway.schema.json"

[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath     = "/health"
healthcheckTimeout  = 5000
healthcheckInterval = 2000

[[services]]
name         = "gateway"
projectPath  = "."
startCommand = "sh -c \"SERVICE=gateway uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}\""
instances    = 1

[[services]]
name         = "martech"
projectPath  = "."
startCommand = "sh -c \"SERVICE=martech uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}\""
instances    = 1

[[services]]
name           = "property"
projectPath    = "."
dockerfilePath = "services/property/Dockerfile"
instances      = 1

[[services]]
name         = "interface"
projectPath  = "interface"
startCommand = "npm start"
instances    = 1
