schema = "https://railway.com/railway.schema.json"

[build]
builder = "DOCKERFILE"
dockerfilePath = "services/python.Dockerfile"

[deploy]
healthcheckPath     = "/health"
healthcheckTimeout  = 5000
healthcheckInterval = 2000

[[services]]
name         = "gateway"
projectPath  = "."
instances    = 1
healthcheckPath = "/health"
[services.buildArgs]
SERVICE = "gateway"

[[services]]
name         = "martech"
projectPath  = "."
instances    = 1
healthcheckPath = "/health"
[services.buildArgs]
SERVICE = "martech"

[[services]]
name           = "property"
instances      = 1
projectPath    = "."
healthcheckPath = "/health"
[services.buildArgs]
SERVICE = "property"

[[services]]
name         = "interface"
projectPath  = "interface"
startCommand = "npm start"
instances    = 1
healthcheckPath = "/health"
