# Root-level Railway config
projectPath = "."
branch = "main"
environment = "production"

[services.unitron]
healthcheckPath = "/health"
autoDeploy = true
dockerfilePath = "services/gateway/Dockerfile"
rootDirectory = "services/gateway"

[services.martech]
healthcheckPath = "/health"
autoDeploy = true
dockerfilePath = "services/martech/Dockerfile"
rootDirectory = "services/martech"

[services.property]
healthcheckPath = "/health"
autoDeploy = true
dockerfilePath = "services/property/Dockerfile"
rootDirectory = "services/property"

[variables]
MARTECH_URL = "https://martech-production-12e1.up.railway.app" # TODO: adjust per environment
