rootDirectory = "."
branch = "main"
[service]
name = "unitron"
rootDirectory = "."
dockerfilePath = "Dockerfile"
startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port \"$PORT\""
healthcheckPath = "/health"
