# Root-level Railway config
rootDirectory = "."
branch = "main"
environment = "production"

# Gateway service
[[services]]
name = "unitron"
rootDirectory = "services/gateway"
projectPath = "services/gateway"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

# Martech service
[[services]]
name = "martech"
rootDirectory = "services/martech"
projectPath = "services/martech"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

# Property service
[[services]]
name = "property"
rootDirectory = "services/property"
projectPath = "services/property"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

[[services]]
name = "insight-agent"
rootDirectory = "services/insight-agent"
projectPath = "services/insight-agent"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"
[[services]]
name = "browse-runner"
rootDirectory = "services/browse-runner"
projectPath = "services/browse-runner"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"
