# Root-level Railway config
# Keep this file in sync with `.github/workflows/railway.yml`.
# Gateway and property services build from the repository root so
# they can copy the shared modules. Their service path in Railway
# should therefore be set to `.`.
rootDirectory = "."
branch = "main"
environment = "production"

# Gateway service
[[services]]
name = "unitron"
rootDirectory = "services/gateway"
dockerfilePath = "services/gateway/Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

# Martech service
[[services]]
name = "martech"
rootDirectory = "services/martech"
projectPath = "services/martech"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

# Property service
[[services]]
name = "property"
rootDirectory = "."
dockerfilePath = "services/property/Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"

[[services]]
name = "insight-agent"
rootDirectory = "services/insight-agent"
projectPath = "services/insight-agent"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"
[[services]]
name = "browse-runner"
rootDirectory = "services/browse-runner"
projectPath = "services/browse-runner"
dockerfilePath = "Dockerfile"
startCommand = "./start.sh"
healthcheckPath = "/health"
