[project]
name = "unitron"

[[service]]
name = "gateway"
root = "services/gateway"
healthcheck_path = "/health"
healthcheck_timeout = 5000
healthcheck_interval = 2000
start_cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"

[[service]]
name = "martech"
root = "services/martech"
healthcheck_path = "/health"
healthcheck_timeout = 5000
healthcheck_interval = 2000
start_cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"
