schema = "https://railway.com/railway.schema.json"

# This global build configuration correctly builds all Python services
# from the root of your repository.
[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/python.Dockerfile"

[deploy]
healthcheckPath     = "/health"
healthcheckTimeout  = 5000
healthcheckInterval = 2000

# --- Service Definitions ---

[[services]]
name         = "gateway"
instances    = 1
env = { SERVICE = "gateway" }

[[services]]
name         = "martech"
instances    = 1
env = { SERVICE = "martech" }

[[services]]
name         = "property"
instances    = 1
env = { SERVICE = "property" }

# The interface service is configured correctly for a Node.js app
# and remains unchanged.
[[services]]
name         = "interface"
projectPath  = "interface"
startCommand = "npm start"
instances    = 1
