schema = "https://railway.com/railway.schema.json"

[build]
builder = "DOCKERFILE"
dockerfilePath = "services/property/Dockerfile"

[deploy]
healthcheckPath     = "/health"
healthcheckTimeout  = 5000
healthcheckInterval = 2000

[[services]]
name         = "gateway"
projectPath  = "."
startCommand = "sh -c \"uvicorn services.gateway.app:app --host 0.0.0.0 --port ${PORT:-8000}\""
instances    = 1

[[services]]
name         = "martech"
projectPath  = "."
startCommand = "sh -c \"uvicorn services.martech.app:app --host 0.0.0.0 --port ${PORT:-8000}\""
instances    = 1

[[services]]
name           = "property"
instances      = 1
projectPath    = "."

[[services]]
name         = "interface"
projectPath  = "interface"
startCommand = "npm start"
instances    = 1
