schema = "https://railway.com/railway.schema.json"

# This global build config is correct. It applies to all services below
# unless they have their own 'projectPath'.
[build]
builder = "DOCKERFILE"
dockerfilePath = "services/python.Dockerfile"

[deploy]
healthcheckPath     = "/ready"
healthcheckTimeout  = 5000
healthcheckInterval = 2000

# --- SERVICE DEFINITIONS ---

[[services]]
name         = "gateway"
instances    = 1
# ADD this command to tell Railway how to run the gateway service.
# REMOVE projectPath and buildArgs.
startCommand = "uvicorn services.gateway.app:app --host 0.0.0.0 --port ${PORT:-8000}"

[[services]]
name         = "martech"
instances    = 1
# ADD this command for the martech service.
# REMOVE projectPath and buildArgs.
startCommand = "uvicorn services.martech.app:app --host 0.0.0.0 --port ${PORT:-8000}"

[[services]]
name         = "property"
instances    = 1
# ADD this command for the property service.
# REMOVE projectPath and buildArgs.
startCommand = "uvicorn services.property.app:app --host 0.0.0.0 --port ${PORT:-8000}"

[[services]]
name         = "interface"
projectPath  = "interface"
builder      = "NIXPACKS"
startCommand = "npm start"
instances    = 1