name: CI
on: [push, pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry install --only main
      - run: poetry run bash -c 'PYTHONPATH=services pytest -q'
      - name: Build interface image
        run: docker build -t interface-image ./interface
      - name: Build property image
        run: docker build -t property-image -f Dockerfile .
      - name: Verify npx exists
        run: docker run --rm interface-image which npx
